### ISSUE TITLE
1.1.6 doesn't have 3D models

### ISSUE THREAD

**Issue by ajawamnet** [antmicro/jetson-orin-baseboard#10]
Unlike 1.0.0 and 1.1.2, 1.1.6 has no 3D models and the PCB has the environment for each footprint set to ${ANT3DMDL}  instead of ${KIPRJMOD}

**Comment by pkatarzynski** [comment]
A 3D model of the Jetson Orin Baseboard in rev.1.1.6 is included in the GH release https://github.com/antmicro/jetson-orin-baseboard/releases/tag/rev.1.1.6-ch

**Comment by ajawamnet** [comment]
No - not the same thing I mean there's no 3D models in the ALTIUM  file.  And the the environment for each footprint set to ${ANT3DMDL} instead of ${KIPRJMOD}
