### ISSUE TITLE
Import to Altium error

### ISSUE THREAD

**Issue by ltidswell** [antmicro/jetson-orin-baseboard#3]
I'm trying to import the files into Altium Designer using the import wizard but the .PcbDoc keeps showing up as empty. The schematics import fine. I get the following logs after the import is complete. Do you have Altium files available / has anyone else had this issue with these files?
[csi.SchLib.LOG](https://github.com/antmicro/jetson-orin-baseboard/files/12480976/csi.SchLib.LOG)
[ethernet.SchLib.LOG](https://github.com/antmicro/jetson-orin-baseboard/files/12480977/ethernet.SchLib.LOG)
[hdmi.SchLib.LOG](https://github.com/antmicro/jetson-orin-baseboard/files/12480978/hdmi.SchLib.LOG)

**Comment by pgielda** [comment]
No, the project files are meant to be used in Kicad (https://en.wikipedia.org/wiki/KiCad). Obviously it is technically possible to import those designs to other tools but this is beyond the scope of this repository / issue tracker -- its meant for reporting bugs / problems with the design only.
