### ISSUE TITLE
Repository does not contain lib folder

### ISSUE THREAD

**Issue by Furukawa-k** [antmicro/jetson-orin-baseboard#6]
I cannot find the kicad library folder in the repository.

**Comment by pkatarzynski** [comment]
Hi Furukawa-k
I saw there was a mention about `lib` folder in README which was a leftover from previous revisions  - thanks for spotting this. 

After we have migrated the PCB design into KiCad 7.x there is no need to keep  local copies of the component libraries as they can be re-created from the project.
You can generate local component libraries with those three major steps 

* In KiCad Schematic Editor select `File -> Export -> Symbols to New Library` 
  *  Include power symbols, select `Project` for Library Table
  * Confirm you want to reassign the schematic component references to the newly created schematic library
* In KiCad PCB Editor select `File -> Export -> Symbols to New Library`
  * Select `Project` for the Library Table
  * Confirm you want to make the fooprints from the design refer to the newly created footprint library 
 * In KiCad PCB Editor select `Tools -> Update Schematic from PCB`
   * In the `Update` section check only `Footprint assignments`

**Comment by Furukawa-k** [comment]
Thank you for indicating the reference.
How can I reference the 3D model?
