### ISSUE TITLE
A lot of those Footprints are really wrong...

### ISSUE THREAD

**Issue by ajawamnet** [antmicro/jetson-orin-baseboard#7]
For instance, the SOD-523 - see the datasheet vs what you have.  
![fpdims](https://github.com/user-attachments/assets/25532a6f-f5b4-4d1e-8784-e19032b73684)
Many of the footprints are incorrect.

**Comment by pkatarzynski** [comment]
Hi ajawamnet

From the snippet you shared I assume you are referring to the recommended mounting footprint of SOD-523 provided by ON Semiconductors (https://www.onsemi.com/pdf/datasheet/rb521s30t1-d.pdf).

We share the SOD-523 footprint  for more diodes in our component library. This footprint definition originates from NXP  (https://www.nxp.com/docs/en/package-information/SOD523.pdf).

Also the recommended SOD-523 pad geometry differs between diode vendors.

I think the biggest recommended SOD-523 package comes from Diodes (https://www.diodes.com/assets/Package-Files/SOD523.pdf) which assumes 0.6x0.7mm pad size.
