### ISSUE TITLE
SW1 part number is incorrect

### ISSUE THREAD

**Issue by ltidswell** [antmicro/jetson-orin-baseboard#8]
The value & footprint for part SW1 is for PN: PCM12SMTR but the MPN listed for this part (and what shows in the BOM) is PN: PCM13SMTR. This part will not fit in the footprint used on the board. If the BOM is used to order this part, it will NOT fit on the board.
![image](https://github.com/user-attachments/assets/37e35600-634b-4120-b9a5-8e524d82ed2a)

**Comment by mizrex** [comment]
It did work in our case. This is the DigiKey part# we used [401-2016-2-ND](https://www.digikey.com/en/products/detail/c-k/PCM12SMTR/1640112)

**Comment by mizrex** [comment]
@ltidswell , yes you are right. I misunderstood your comment earlier.

**Comment by pkatarzynski** [comment]
Hi ltidswell.  

We have unified the SW1 MPN into PCM12SMTR. Thanks for spotting that.
