### ISSUE TITLE
Bluetooth won't come up on a M.2 Wifi/BT card

### ISSUE THREAD

**Issue by mizrex** [antmicro/jetson-orin-baseboard#9]
Firstly, great work on this project! Very nicely done and documented. 
We tried connecting a Wifi6 and also a Wifi5 Intel M.2. cards to J1 Key-E on the board. While the Wifi came up fine after installing their drivers. We are not able to get the Bluetooth working. 
I did see that the SDIO pins are not connected (only major difference compare to the Jetson Orin Nano dev kit). But I'm not sure if Bluetooth uses the SDIO. 
If you happen to have any idea on this?

**Comment by mizrex** [comment]
Could it be something related to this USB connection:
If R20 and R52 needs to be populated?
![Bluetooth](https://github.com/user-attachments/assets/538ed4c1-8ff2-4eb0-b412-3ac6439b44cc)

**Comment by mizrex** [comment]
We tried connecting R20 and R52, from my previous post. The Bluetooth LED (D52), started glowing, and M.2 card started showing up under _lsusb_ . However, it won't activate or turn on(even after drivers were installed). _hcitool dev_ cannot find any local bluetooth hardware connected. Any idea on this?

**Comment by mizrex** [comment]
@pkatarzynski , thank you for getting back. This is [the Wifi+BT card](https://www.intel.com/content/www/us/en/products/sku/130293/intel-wifi-6-ax201-gig/specifications.html) we are using.
@pgielda , please see the lsusb and lspci outputs below. I think the wifi came up fine on the PCIE, while the bluetooth came up on the USB (after we connected R20 and R52). However, the bluetooth doesn't come up (even after installing it's drivers). Wifi works fine.
![lsusblspci](https://github.com/user-attachments/assets/7dae6b37-0566-436a-9f03-030530f51647)

**Comment by pkatarzynski** [comment]
Please verify if the Bluetooth interface is not soft-blocked. 

You can use  `rfkill list` for that. 
You can unblock the device with `rfkill unblock all`

After that the Bluetooth device should become visible after calling  `hcitool dev`

We have checked this approach with Waveshare AW-CB375NF WiFi/BT M.2 card Jetson Orin Baseboard in [Rev.1.1.6](https://github.com/antmicro/jetson-orin-baseboard/releases/tag/rev.1.1.6-ch) and the reference BSP image mentioned in the [Getting Started](https://antmicro.github.io/jetson-orin-baseboard/getting_started.html#get-the-bsp-image) section of the documentation.

**Comment by zonga501** [comment]
Hello, Working with mizrex and the device seems to not be blocked but is also not showing 
![BTissue](https://github.com/user-attachments/assets/637a70f8-38f5-4623-b1fb-19321d08183d)
